[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Group 2D Setap Project - University Timetable Generator"
authors = [{name = "Jack", email = "up2111450@myport.ac.uk"}]
dynamic = ["version", "description"]
